<?php
require __DIR__ . '/../includes/bootstrap.php'; require_admin();
$id=(int)($_GET['id']??$_POST['id']??0); $record=null; $error='';
if($id){$s=db()->prepare('SELECT * FROM sick_leaves WHERE id=?');$s->execute([$id]);$record=$s->fetch();if(!$record){http_response_code(404);exit('السجل غير موجود.');}}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    $data=[
      'service_code'=>trim($_POST['service_code']??''),'identity_number'=>trim($_POST['identity_number']??''),'patient_name'=>trim($_POST['patient_name']??''),'companion_name'=>trim($_POST['companion_name']??''),'relationship'=>trim($_POST['relationship']??''),'issue_date'=>$_POST['issue_date']??'','leave_from'=>$_POST['leave_from']??'','leave_to'=>$_POST['leave_to']??'','physician_name'=>trim($_POST['physician_name']??''),'physician_specialty'=>trim($_POST['physician_specialty']??''),'is_active'=>isset($_POST['is_active'])?1:0
    ];
    if($data['service_code']===''||$data['identity_number']===''||$data['patient_name']===''||$data['issue_date']===''||$data['leave_from']===''||$data['leave_to']===''){$error='أكمل الحقول المطلوبة.';}
    elseif($data['leave_to']<$data['leave_from']){$error='تاريخ نهاية الإجازة لا يمكن أن يسبق تاريخ البداية.';}
    else{
      try{$days=duration_days($data['leave_from'],$data['leave_to']);
        if($id){$sql='UPDATE sick_leaves SET service_code=?,identity_number=?,patient_name=?,companion_name=?,relationship=?,issue_date=?,leave_from=?,leave_to=?,duration_days=?,physician_name=?,physician_specialty=?,is_active=? WHERE id=?';$vals=[$data['service_code'],$data['identity_number'],$data['patient_name'],$data['companion_name']?:null,$data['relationship']?:null,$data['issue_date'],$data['leave_from'],$data['leave_to'],$days,$data['physician_name']?:null,$data['physician_specialty']?:null,$data['is_active'],$id];db()->prepare($sql)->execute($vals);audit('update_record',$id,['service_code'=>$data['service_code']]);$_SESSION['flash']='تم تعديل السجل.';}
        else{$sql='INSERT INTO sick_leaves (service_code,identity_number,patient_name,companion_name,relationship,issue_date,leave_from,leave_to,duration_days,physician_name,physician_specialty,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)';$vals=[$data['service_code'],$data['identity_number'],$data['patient_name'],$data['companion_name']?:null,$data['relationship']?:null,$data['issue_date'],$data['leave_from'],$data['leave_to'],$days,$data['physician_name']?:null,$data['physician_specialty']?:null,$data['is_active']];db()->prepare($sql)->execute($vals);$id=(int)db()->lastInsertId();audit('create_record',$id,['service_code'=>$data['service_code']]);$_SESSION['flash']='تمت إضافة السجل.';}
        header('Location: '.base_url('/admin/index.php'));exit;
      }catch(PDOException $e){$error=$e->getCode()==='23000'?'يوجد سجل بنفس رمز الخدمة ورقم الهوية.':'تعذر حفظ السجل. تأكد من تشغيل upgrade.php مرة واحدة بعد استبدال الملفات.';}
    }
    $record=array_merge($record?:[],$data);
}
$r=$record?:['service_code'=>'','identity_number'=>'','patient_name'=>'','companion_name'=>'','relationship'=>'','issue_date'=>date('Y-m-d'),'leave_from'=>date('Y-m-d'),'leave_to'=>date('Y-m-d'),'physician_name'=>'','physician_specialty'=>'','is_active'=>1];
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$id?'تعديل سجل':'إضافة سجل'?></title><link rel="stylesheet" href="<?=e(base_url('/assets/admin.css'))?>"></head><body class="admin-body"><header class="admin-top"><strong><?=$id?'تعديل سجل':'إضافة سجل جديد'?></strong><a href="<?=e(base_url('/admin/index.php'))?>">العودة للسجلات</a></header><main class="admin-container"><section class="panel"><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><label class="field">رمز الخدمة *<input name="service_code" required maxlength="40" value="<?=e($r['service_code'])?>"></label><label class="field">رقم الهوية / الإقامة *<input name="identity_number" required maxlength="20" value="<?=e($r['identity_number'])?>"></label><label class="field">الاسم *<input name="patient_name" required maxlength="180" value="<?=e($r['patient_name'])?>"></label><label class="field">اسم المرافق<input name="companion_name" maxlength="180" value="<?=e($r['companion_name']??'')?>"></label><label class="field">صلة القرابة<input name="relationship" maxlength="120" value="<?=e($r['relationship']??'')?>"></label><label class="field">تاريخ إصدار تقرير الإجازة *<input type="date" name="issue_date" required value="<?=e($r['issue_date'])?>"></label><label class="field">تبدأ من *<input type="date" name="leave_from" required value="<?=e($r['leave_from'])?>"></label><label class="field">وحتى *<input type="date" name="leave_to" required value="<?=e($r['leave_to'])?>"></label><label class="field">اسم الطبيب<input name="physician_name" maxlength="180" value="<?=e($r['physician_name'])?>"></label><label class="field">المسمى الوظيفي للطبيب<input name="physician_specialty" maxlength="180" value="<?=e($r['physician_specialty'])?>"></label><label class="field full"><span>الحالة</span><span><input style="width:auto;height:auto" type="checkbox" name="is_active" value="1" <?=$r['is_active']?'checked':''?>> نشط ويظهر في الاستعلام</span></label><div class="actions full"><button class="btn" type="submit">حفظ</button><a class="btn secondary" href="<?=e(base_url('/admin/index.php'))?>">إلغاء</a></div></form></section></main></body></html>
