<?php
require __DIR__ . '/../includes/bootstrap.php'; require_admin();
$q=trim($_GET['q']??''); $status=$_GET['status']??'all'; $page=max(1,(int)($_GET['page']??1)); $perPage=20; $offset=($page-1)*$perPage;
$where=[];$params=[];
if($q!==''){ $where[]='(service_code LIKE ? OR identity_number LIKE ? OR patient_name LIKE ? OR companion_name LIKE ? OR relationship LIKE ? OR physician_name LIKE ?)'; $like='%'.$q.'%'; array_push($params,$like,$like,$like,$like,$like,$like); }
if($status==='active'){$where[]='is_active=1';}elseif($status==='inactive'){$where[]='is_active=0';}
$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$countStmt=db()->prepare("SELECT COUNT(*) FROM sick_leaves $whereSql");$countStmt->execute($params);$total=(int)$countStmt->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));
$stmt=db()->prepare("SELECT * FROM sick_leaves $whereSql ORDER BY id DESC LIMIT $perPage OFFSET $offset");$stmt->execute($params);$records=$stmt->fetchAll();
$stats=db()->query('SELECT COUNT(*) total, SUM(is_active=1) active_count, SUM(is_active=0) inactive_count FROM sick_leaves')->fetch();
$flash=$_SESSION['flash']??'';unset($_SESSION['flash']);
?><!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>لوحة الإدارة</title><link rel="stylesheet" href="<?=e(base_url('/assets/admin.css'))?>"></head><body class="admin-body"><header class="admin-top"><strong>لوحة إدارة الإجازات — نموذج تجريبي</strong><div class="actions"><a href="<?=e(base_url('/'))?>">عرض الموقع</a><a href="<?=e(base_url('/admin/audit.php'))?>">سجل العمليات</a><a href="<?=e(base_url('/admin/logout.php'))?>">تسجيل الخروج</a></div></header><main class="admin-container">
<div class="toolbar"><h1>السجلات</h1><a class="btn" href="<?=e(base_url('/admin/edit.php'))?>">+ إضافة سجل</a></div><?php if($flash):?><div class="alert success"><?=e($flash)?></div><?php endif;?>
<div class="stats"><div class="stat"><span>إجمالي السجلات</span><strong><?=e((string)($stats['total']??0))?></strong></div><div class="stat"><span>النشطة</span><strong><?=e((string)($stats['active_count']??0))?></strong></div><div class="stat"><span>المعطلة</span><strong><?=e((string)($stats['inactive_count']??0))?></strong></div></div>
<section class="panel"><form method="get" class="filter-row"><input name="q" value="<?=e($q)?>" placeholder="بحث بالرمز أو الهوية أو الاسم أو المرافق أو صلة القرابة أو الطبيب"><select name="status"><option value="all" <?=$status==='all'?'selected':''?>>الكل</option><option value="active" <?=$status==='active'?'selected':''?>>نشط</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>معطل</option></select><button class="btn" type="submit">بحث</button></form></section>
<section class="panel table-wrap"><table class="table"><thead><tr><th>الرمز</th><th>الهوية</th><th>الاسم</th><th>الفترة</th><th>المدة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody><?php if(!$records):?><tr><td colspan="7">لا توجد سجلات.</td></tr><?php endif;?><?php foreach($records as $r):?><tr><td class="code"><?=e($r['service_code'])?></td><td><?=e(substr($r['identity_number'],0,3).'••••'.substr($r['identity_number'],-3))?></td><td><?=e($r['patient_name'])?></td><td><?=e($r['leave_from'])?> ← <?=e($r['leave_to'])?></td><td><?=e((string)$r['duration_days'])?></td><td><span class="badge <?=$r['is_active']?'on':'off'?>"><?=$r['is_active']?'نشط':'معطل'?></span></td><td><div class="actions"><a class="btn small" href="<?=e(base_url('/admin/edit.php?id='.(int)$r['id']))?>">تعديل</a><form class="inline" method="post" action="<?=e(base_url('/admin/toggle.php'))?>"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e((string)$r['id'])?>"><button class="btn small warn" type="submit"><?=$r['is_active']?'تعطيل':'تفعيل'?></button></form><form class="inline" method="post" action="<?=e(base_url('/admin/delete.php'))?>" onsubmit="return confirm('هل تريد حذف هذا السجل نهائيًا؟');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e((string)$r['id'])?>"><button class="btn small danger" type="submit">حذف</button></form></div></td></tr><?php endforeach;?></tbody></table>
<?php if($pages>1):?><div class="pagination"><?php for($i=1;$i<=$pages;$i++):$qs=http_build_query(['q'=>$q,'status'=>$status,'page'=>$i]);?><a class="<?=$i===$page?'current':''?>" href="?<?=e($qs)?>"><?=$i?></a><?php endfor;?></div><?php endif;?></section></main></body></html>
